### ISSUE TITLE
Reflect CRAN's official policy about Rust

### ISSUE THREAD

**Issue by yutannihilation** [r-rust/faq#2]
Recently, CRAN repository policy now has the document titled "Using Rust in CRAN packages."

https://cran.r-project.org/web/packages/using_rust.html

It seems this document is not very polished at the moment, but I think this FAQ needs to somehow reflect what they say, either by accepting or rejecting the suggestions carefully.

But, before reflecting it, it might be better to discuss whether their suggestions are valid. I already sent [some feedback](https://stat.ethz.ch/pipermail/r-package-devel/2023q3/009346.html) to them, but the document might still contain questionable points, so, if you have something to say on this, you should give your feedback to them, though it would require so much energy.

**Comment by jeroen** [comment]
Thanks for trying to steer them in the right direction! The policy does not make much sense to me but I don't think they will listen if I send any feedback.

As others have stated on the mailing lists, relying on the cargo `.lock` files and official `crates.io` archives is probably the most reliable and future proof way to embed the crates. Definitely much better than "hosted at a long-term secure site under the maintainer’s control" as suggested in the policy. But of course we don't make the rules :)

I have added a link to this document in the faq text, thanks for bringing it up!

**Comment by yutannihilation** [comment]
Thanks. I was hoping the policy would be more reasonable at the time of filing this. But, now I think just linking is enough.
